"""Adjust relationships and back_populates

Revision ID: 71d14a097c07
Revises: 4a62d28caadb
Create Date: 2024-01-11 16:54:40.847500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d14a097c07'
down_revision: Union[str, None] = '4a62d28caadb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bidding_room_bidder_bidder_id_fkey', 'bidding_room_bidder', type_='foreignkey')
    op.drop_constraint('bidding_room_bidder_room_id_fkey', 'bidding_room_bidder', type_='foreignkey')
    op.drop_constraint('bidding_rooms_current_highest_bidder_id_fkey', 'bidding_rooms', type_='foreignkey')
    op.drop_constraint('bidding_rooms_owner_id_fkey', 'bidding_rooms', type_='foreignkey')
    op.drop_constraint('chat_messages_room_id_fkey', 'chat_messages', type_='foreignkey')
    op.drop_constraint('chat_messages_sender_id_fkey', 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'bidding_room_bidder', 'bidding_rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bidding_room_bidder', 'users', ['bidder_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bidding_rooms', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'bidding_rooms', 'users', ['current_highest_bidder_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'chat_messages', 'bidding_rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_messages', 'users', ['sender_id'], ['id'], ondelete='SET NULL')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'bidding_rooms', type_='foreignkey')
    op.drop_constraint(None, 'bidding_rooms', type_='foreignkey')
    op.drop_constraint(None, 'bidding_rooms', type_='foreignkey')
    op.drop_constraint(None, 'bidding_room_bidder', type_='foreignkey')
    op.drop_constraint(None, 'bidding_room_bidder', type_='foreignkey')
    op.create_foreign_key('bidding_room_bidder_room_id_fkey', 'bidding_room_bidder', 'bidding_rooms', ['room_id'], ['id'])
    op.create_foreign_key('bidding_room_bidder_bidder_id_fkey', 'bidding_room_bidder', 'users', ['bidder_id'], ['id'])
    op.create_foreign_key('bidding_rooms_current_highest_bidder_id_fkey', 'bidding_rooms', 'users', ['current_highest_bidder_id'], ['id'])
    op.create_foreign_key('bidding_rooms_owner_id_fkey', 'bidding_rooms', 'users', ['owner_id'], ['id'])
    op.create_foreign_key('chat_messages_sender_id_fkey', 'chat_messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key('chat_messages_room_id_fkey', 'chat_messages', 'bidding_rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###
